[project]
name = "webserver"
version = "1.0.0"
description = "PDF to Image conversion service"
dependencies = ["flask"]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
